version: '1'
services:
  dev-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mvx_root
      MYSQL_DATABASE: mvx
      MYSQL_USER: mvx_andrei
    ports:
      - "3356:3306"
    volumes:
      - mvx_transactions_data:/var/lib/mysql
    command: --log-error-verbosity=3

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  redis:
    image: redis:7

  
  mvx-transactions:
    build: 
      context: .
      dockerfile: ./apps/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001

    env_file:
      - ./.env
    depends_on:
      - dev-db
      - rabbitmq
      - redis
  
volumes:
  mvx_transactions_data: